// <auto-generated />
using ITMappingSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ITMappingSystem.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20231107151816_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ITMappingSystem.Models.Computer", b =>
                {
                    b.Property<int>("computerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("computerID"));

                    b.Property<string>("computerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("computerID");

                    b.ToTable("Computers");
                });
#pragma warning restore 612, 618
        }
    }
}
